config/routes.rb
Rails.application.routes.draw do

  post 'pay2go/return'
  post 'pay2go/notify'

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :orders

  namespace :admin do
    resources :orders
  end

  get '/events/search' => 'events#search'

  devise_for :users

  resources :events do
    resources :reviews 
    resources :posts
  end

  resources :orders do
    member do
      post :checkout_pay2go
    end

    collection do
      post :checkout_pay2go
    end
  end

  root 'events#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items
  has_many :products, :through => :line_items
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  #has_many :comments
  has_many :reviews
  has_many :posts
  has_many :event_groupships 
  has_many :groups, :through => :event_groupships
  has_one :location
  validates_presence_of :bookname

end

app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
  belongs_to :event
  belongs_to :group

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :event_groupships
  has_many :events, :through => :event_groupships
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  belongs_to :cart
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :event
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  has_many :products, :through => :line_items
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  serialize :params, JSON

  belongs_to :order

  def self.find_and_process(params)
    result = JSON.parse( params['Result'] )

    payment = self.find(result['MerchantOrderNo'].to_i)
    payment.paid = params['Status'] == 'SUCCESS'
    payment.params = params
    payment
  end

  def deadline
    Time.now + 3.days
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :event
  validates_presence_of :name
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, :only => [ :show, :edit, :update, :destroy]


  def index
    @event = Event.new
    @events = Event.page(params[:page]).per(5)

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Book was successfully created"
      redirect_to events_path
    else
      render :action => :new
    end
  end

  def show
    @page_title = @event.bookname
    @reviews = Review.where(event_id: @event)
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def edit

    @events = Event.page(params[:page]).per(5)
    render :index
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "Book was successfully updated"
      redirect_to event_path(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @event.destroy
    flash[:alert] = "Book was successfully deleted"
    redirect_to events_path
  end

  def search
    @search_q = params[:q]
    # @events = Event.search @search_q
    @events = Event.where(:bookname => @search_q)

    respond_with @events
  end


  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:bookname,:author,:description)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :get_cart

  def show
    @order = current_user.orders.find( params[:id] )
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new( order_params )

    @cart.line_items.each do |line|
      @order.line_items.build( :product => line.product, :qty => line.qty )
    end

    amount = 0
    @cart.line_items.each do |line|
      amount +=  line.product.price * line.qty
    end
    @order.amount = amount

    if @order.save

      session[:cart_id] = nil

      redirect_to products_path
    else
      render :new
    end
  end

  protected

  def order_params
    params.require(:order).permit(:name, :email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @post = @event.posts.create(params[:post].permit(:name, :body))

    redirect_to event_path(@event)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>



<div class="form-group">
  <%= f.label :bookname, "Name" %>
  <%= f.text_field :bookname, :class=>"form-control" %>
</div>

<div class="form-group">
  <%= f.label :author, "Author" %>
  <%= f.text_field :author, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, :class => "form-control"  %>
</div>

app/views/events/edit.html.erb
<%= form_for @event,:url => event_path(@event), :method=>:patch, :class => "form" do |f| %>

  <%= render :partial=> 'form', :locals=>{:f=>f} %>
  <%= f.submit "Update", :class => "btn btn-primary"  %>
<% end %>

app/views/events/index.html.erb
<h1>Mybook system</h1>



<%= form_for @event  do |f| %>

  <div class="form-group">
    <%= f.label :bookname, "Name" %>
    <%= f.text_field :bookname, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author, "Author" %>
    <%= f.text_field :author, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :class => "form-control"  %>
  </div>

  <%= f.submit "Create" %>
<% end %>

<table class="table">
  <tr>
    <td><h3>Book Name</h3></td>
    <td><h3>star</h3></td>
    <td><h3>Show Detail</h3></td>
    <td><h3>Edit Book</h3></td>
    <td><h3>Delete Book</h3></td>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td>
        <%= event.bookname %>
      </td>
      <td>
        <p class="star-rating" data-score=<%= @avg_rating %>></p>
      </td>
      <td>
        <%= link_to 'Show', event_path(event),:class=> "btn btn-default"%>
      </td>
      <td>
        <%= link_to 'Edit', edit_event_path(event),:class=> "btn btn-default" %>
      </td>
      <td>
        <%= link_to 'Delete', event_path(event), :method=> :delete, :class=> "btn btn-default" %>
      </td>
    </tr>
  <% end %>

</table>
<%= link_to 'New Event', new_event_path %></br>

<%= paginate @events %>

<% content_for :edit do %>

  <%= form_tag("/events/search", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %>

<% end %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
  <h2> New </h2>
  <%= render :partial=> 'form', :locals=>{:f=>f} %>
  </br>
  <%= f.submit "Create" %>
<% end %>

app/views/events/search.html.erb
<%=simple_format(@event.bookname) %>
<%= simple_format(@event.author) %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/events/show.html.erb
<%=simple_format(@event.bookname) %>
<%= simple_format(@event.author) %>
<%= simple_format(@event.description) %>
Created time <%= (@event.created_at) %> 
<p><%= link_to 'Back to index', events_path %></p>

<p><%= link_to 'Give reviews', new_event_review_path(@event) %></p>
<p class="star-rating" data-score=<%= @avg_rating %>></p>
<h3>Reviews</h3>
<% @reviews.each do |r| %>
  <%= r.comment %>
  <%= r.rating %>
<% end %>

<div id="comments">
  <h4><%= @event.posts.count %> Comments</h4>
  <%= render @event.posts %>

  <h3>Add a comment:</h3>
  <%= render "posts/form" %>
</div>

app/views/posts/_form.html.erb
<%= form_for([@event, @event.posts.build]) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/_post.html.erb
<p class="comment_name"><strong><%= post.name %></strong></p>
<p ><%= post.body %></p>
<p ><%= post.body %></p>
<p ><%= post.body %></p>