config/routes.rb
Rails.application.routes.draw do

  post 'pay2go/return'
  post 'pay2go/notify'

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :orders

  namespace :admin do
    resources :orders
  end

  get '/events/search' => 'events#search'

  devise_for :users

  resources :events do
    resources :reviews 
    resources :posts
  end

  resources :orders do
    member do
      post :checkout_pay2go
    end

    collection do
      post :checkout_pay2go
    end
  end

  root 'events#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items
  has_many :products, :through => :line_items
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  #has_many :comments
  has_many :reviews
  has_many :posts
  has_many :event_groupships 
  has_many :groups, :through => :event_groupships
  has_one :location
  validates_presence_of :bookname

end

app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
  belongs_to :event
  belongs_to :group

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :event_groupships
  has_many :events, :through => :event_groupships
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  belongs_to :cart
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :event
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  has_many :products, :through => :line_items
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  serialize :params, JSON

  belongs_to :order

  def self.find_and_process(params)
    result = JSON.parse( params['Result'] )

    payment = self.find(result['MerchantOrderNo'].to_i)
    payment.paid = params['Status'] == 'SUCCESS'
    payment.params = params
    payment
  end

  def deadline
    Time.now + 3.days
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :event
  validates_presence_of :name
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Mybook" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% if flash[:notice].present? %>
            <div class="alert alert-success" role="alert">
              <%= flash[:notice]%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% if flash[:alert].present? %>
            <div class="alert alert-danger" role="alert">
              <%= flash[:alert]%>
            </div>
          <% end %>

        </div>
      </div>
    </div>

    <% if current_user %>
      Hi, <%= current_user.email %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
  <% end %>

  <p><h3><%= link_to "Products", products_path %></h3></p>

  <%= yield %>
  <div id="edit">
    <%= yield :edit %>
  </div>

  <script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function(){
    return $(this).attr('data-score');
  }
});
  </script>

  </body>
</html>